project_name : "ProatacProject"
project_dir : "ProatacDir"
analysis_person : "Caleb Lareau"
sequencing_runs : 
  - name : "Run1"
    version : 'v2'
    dir : "/data/aryee/caleb/indrops/20170503_David_and_Vidya/o2"
    fastq_path : "{library_prefix}_{split_affix}_{read}_001.fastq.gz"
    split_affixes : ["L001", "L002", "L003", "L004"]
    libraries : 
#      - {library_name: "S1", library_prefix: "S1_S4"}
      - {library_name: "M1_S8", library_prefix: "M1_S8"}
paths : 
  bowtie_index : "/data/aryee/caleb/indrops/indrops/HS/bowtie_index"
  python_dir : ""
  samtools_dir : ""
  rsem_dir : ""
  java_dir : ""
parameters : 
# OPTIONAL PARAMETERS
#   refGenomeFiles:
#     tss : pathToTSSFile.bed # 
#     blacklist : pathToBlacklistFile.bed # 
#   output_arguments:
#     output_unaligned_reads_to_other_fastq: False
#     low_complexity_mask: False
#   bowtie_arguments:
#     m : 200
#     n : 1
#     l : 15
#     e : 1000
  trimmomatic_arguments:
    LEADING: "28"
    SLIDINGWINDOW: "4:20"
    MINLEN: "16"
