extra_fn_clean_exts:
    - '.myformat'
    - '_processedFile'
extra_fn_clean_trim:
    - '.trim'
    - '.temp2'
    - '_1'
    - '_2'
picard/insertsize:
    fn: '*.MarkDuplicates.log'
    shared: true

