extra_fn_clean_exts:
    - '.myformat'
    - '_processedFile'
extra_fn_clean_trim:
    - '.trim'
    - '.proatac'
    - '.temp2'
    - '_1'
    - '_2'
picard/markdups:
    fn: '*.MarkDuplicates.log'
    shared: true
picard/insertsize:
    fn: '*.inserts.log'
    shared: true
custom_logo: '/Volumes/dat/Research/BuenrostroResearch/lareau_dev/proatac/proatac/anno/multiqc/logo.png'
custom_logo_url: 'http://proatac.readthedocs.io'
custom_logo_title: 'proatac'
report_header_info:
    - For more information on proatac: 'http://proatac.readthedocs.io'
top_modules:
    - 'fastqc'
    - 'bowtie2'
    - 'picard'
fn_ignore_dirs:
    - 'macs2'
read_count_multiplier: 0.001
read_count_prefix: 'Total'
read_count_desc: 'Thousands'
title: "proatac QC report"
subtitle: "An overview of key metrics for ATAC-seq analysis processing statistics."
intro_text: ""
report_comment: ""
max_table_rows: 100
table_columns_visible:
    FastQC:
        percent_duplicates: False
custom_data:
    ATAC_stats:
        id: 'ATAC_stats'
        section_anchor: 'ATAC_stats'
        section_name: 'ATAC-seq QC stats'
        description: 'important QC metrics for ATAC-seq'
        file_format: 'tsv'
        plot_type: 'table'
    tss_coverage:
        file_format: 'tsv'
        section_name: 'TSS Plot'
        description: 'Insertions near (signed) RefSeq Transcription Start Sites'
        plot_type: 'linegraph'
        pconfig:
            id: 'example_coverage_lineplot'
            title: 'TSS Plot'
            ylab: 'Number of Insertions'
            xlab: 'Postion relative to TSS'
            xmax: 2000
            ymin: -2000
sp:
    ATAC_stats:
        fn: '*sampleQC.tsv'
    tss_coverage:
        fn: '*tss.tsv'
    